#!/usr/bin/python3

    print("What's your name?" :")
    name = input("> ")
    
    if name:
        print('Welcome {name}')
    else:


questions = [('Question 1', 'Answer'),
             ('Question 2', 'Answer')
    ]

def showInstructions():
    print('''
Escpae Room Game
OBJECTIVE: Escape from thress rooms and survive!
--------
Actions:
    LOOK
    READ [item]
    GO [north]
    GET [item, spell]
    
Type 'help' at any time! Type 'q' to quit!''')


no_of_questions = len(questions)
game_over = False
i = 0

while game_over == False:
    
    if i + 1 > no_of_questions:
        print('You win!')
        break
    
    if input(questions[i][0]) == questions[i][1]:
        print('Correct!')
        i += 1
    else:
        print('Wrong answer! Game over!')


rooms = {

            'Room1' : {
                  'item'  : 'key'
                  'item'  : 'note'
                  'item'  : 'book'
                  'desc'  : 'You are in a room that appears to be a personal office, there is a large mahognay desk and leather chair. The windows have been covered and blacked out. The is one door, 

                },

            'Room2' : {
                  'north' : 'Hall',
                  'east'  : 'Dining Room',
                  'south' : 'Garden',
                  'west'  : 'Pantry',
                  'item'  : 'monster',
                },
            'Room3' : {
                  'south' : 'Dining Room',
                  'west'  : 'Hall',
                },

        game_over = True
